# Site settings
title:          Kyuseong
description:    "Kyuseong's blog"
baseurl:        "/"
url:            "https://kyuseong.github.io/"

# Author
author:
  name:         Kyuseong
  url:          https://kyuseong.github.io/
  email:        laster40@naver.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
